---
- name: Configure frontend servers
  hosts: frontend
  become: yes
  vars:
    backend_server: "35.175.190.0"
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Enable nginx via amazon-linux-extras
      command: amazon-linux-extras enable nginx1
      args:
        creates: /etc/yum.repos.d/amzn2extra-nginx1.repo

    - name: Install NGINX
      yum:
        name: nginx
        state: present

    - name: Configure NGINX proxy
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
